services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: banana
      MARIADB_DATABASE: faf-icebreaker
      MARIADB_USER: faf-icebreaker
      MARIADB_PASSWORD: banana
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_VHOST: /faf-core
      RABBITMQ_DEFAULT_USER: faf-icebreaker
      RABBITMQ_DEFAULT_PASS: banana
    ports:
      - "5672:5672"
